#!/usr/bin/env bash
# This script makes localhost resolve to 127.0.0.2 and facebook.com resolve to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i.bak 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i.bak '/localhost/ a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
