#!/usr/bin/env bash
# This script makes localhost resolve to 127.0.0.2 and facebook.com resolve to 8.8.8.8
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts2.new
echo "8.8.8.8 facebook.com" >> ~/hosts2.new
cp -f ~/hosts2.new /etc/hosts
cat ~/hosts.new >> /etc/hosts
